### ISSUE TITLE
suggestion(vegging): vegging is too quick, and without warning

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#122]
by [sid](https://discord.com/channels/1047222060667125810/1062744292772286474)

The ending of each day is too abrupt and a lot of people are vegging. I see the issue with kicks as some would "hold the game hostage", but perhaps a visual warning that's more apparent than the small timer for those without sound on would be helpful.

100% agreed. I veg so much because I don't notice the timer is almost out, since there's no visual way to tell without looking up and reading the numbers. Kicks is easy to notice without having to check it, and means the convo can continue even if you've run out of extends. even something like a system message of "only fifteen seconds left until you veg! vote!!!!!!!" would be useful. also I wish it would let you stay in a game if you veg. i'm never sure if i vegged or if i hit the wrong button on my mouse

yeah a 1 minute, 30 second, 15 second system message with advice to /extend if needed would be lovely
getting kicked straight out of the game also probably makes it hard for new players to learn what went wrong - they never see the message that they turned into a vegetable

---
suggestion 1: kicks; very highly requested
suggestion 2: a more apparent visual warning, e.g. a message in the chat when the timer is about to be up (1min/30s/15s)

**Comment by r3ndd** [comment]
I would be fine with replacing the extension system with a kicks system. 100 token bounty for a polished implementation.

**Comment by pikulet** [comment]
When everyone but one guy has voted, the timer drops to 30s. We can increase this to 60s first and see the feedback. It will be a quick fix that can reduce some of the unintended vegging.

`Games/types/Mafia/meetings/Village.js`

**Comment by pikulet** [comment]
@DrSharky claims tokenz remember
