### ISSUE TITLE
bugs(caroler): Problems affecting the targets of Caroler

### ISSUE THREAD

**Issue by R9H9** [r3ndd/BeyondMafia-Integration#129]
by [Giga](https://beyondmafia.com/community/forums/thread/tbQ8YNKC2C?reply=Kvvufc3KU)
Bug Description: Caroler can carol the same person twice in a row; they shouldn't be able to
by [chiyoko](https://beyondmafia.com/community/forums/thread/tbQ8YNKC2C?reply=0bwPvIVPy)
Bug Description: visiting mafia get carols
by [chiyoko](https://beyondmafia.com/community/forums/thread/tbQ8YNKC2C?reply=GPLiC_Dj8)
Bug Description: apparently caroler self visited twice

**Comment by r3ndd** [comment]
I think these are somewhat ambiguous bugs. I'm not seeing in that game review where the caroler visited twice, but maybe I'm misinterpreting what that means. Visiting mafia getting carols I think stems from the fact that only one mafia member actually visits during the kill. I'm also not able to replicate the bug that allows the caroler to carol the same person twice in a row; this should already be addressed by the functional exclusion feature.
