### ISSUE TITLE
refactor: use constant files

### ISSUE THREAD

**Issue by r3ndd** [r3ndd/BeyondMafia-Integration#142]
@pikulet Created constant files for things like tags, flags, and states, viewable under Games/types/Mafia/const. Refactoring the code to use these constants would be nice.

**Comment by r3ndd** [comment]
40 token bounty for this.

**Comment by pikulet** [comment]
It is clumsy and not readable so we will use documentation to record all the labels instead. 

Will keep const files for action priority and meeting priority.
