### ISSUE TITLE
Bug: Agent can have list of names too large for the page

### ISSUE THREAD

**Issue by DrSharky** [r3ndd/BeyondMafia-Integration#15]
Game: Mafia

Role: Agent

Description of issue: When playing Agent, you can sometimes get a list of people to whisper to and roles to contact that becomes too large for the webpage. If the player selects a role to contact towards the bottom, it may be that they can no longer select "Say to everyone" again. When facing this bug, I noticed you could whisper dead players and roles. Removing the dead from the available list would fix this for most games. However, a better solution should be reached eventually, as the max player limit is 50.

Reproduction steps: Start Mafia game with Agent role and enough players. I don't know the specific player amount required, but a 12-person game is enough for it to occur. As Agent, test out the Say/Whisper menu. Over a couple of in-game days, contact different roles, and check to see if the Say/Whisper menu can be used to contact the dead. Select an option towards the bottom of the menu. At this point, it will be likely that you cannot select "Say to everyone" any longer.

**Comment by r3ndd** [comment]
20 token bounty for this. Also for those looking to fix this, it's technically called Telepath/Psychic on BM.
