### ISSUE TITLE
suggestion(forum,notification): tag players and send notifications to them

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#17]
[ref](https://beyondmafia.com/community/forums/thread/D7WabRG0F1) suggested by DkKoba.

This is a request that is mainly aimed to help with moderation for the report system but will also help users reply/bring people into the conversation that they wish, as well as help for forum gameplay.

Essentially asking for a system of being able to type "@(username)" and it sending a notification to a player. 

(Also should note that read notifications don't seem to have a way of being seen after dismissing them)

**Comment by r3ndd** [comment]
This is already a thing. Is it not working?

**Comment by r3ndd** [comment]
It's the reason why you get notified when someone replies to you.

**Comment by pikulet** [comment]
i see, okay, yes I do get notifications if im the poster of the thread! i'll close this issue.

by the way, i'm just scrolling through suggestions and posting up the more popular ones with upvotes and all to give them more visibility/ if anyone else wants to start working on them
