### ISSUE TITLE
suggestion(frontend): add role description in setup display

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#19]
by [Firefly7](https://beyondmafia.com/community/forums/thread/IcXe6iehme?reply=z7BDTP5T8Ar)

Would be nice if clicking a role's icon in the role list for a setup returned the role's description like it does when you click the role icon by a dead player

---
referring to the in-game setup display at the top right corner
![image](https://user-images.githubusercontent.com/24848927/211083852-25d5652e-b72a-4a4f-8a14-28e8e241b246.png)

**Comment by r3ndd** [comment]
50 token bounty for whoever figures out and implements a good method to do this while still having a setup popover. Ideally it would be within the setup popover where you can browse all possible roles (particularly for the sandbox setups).

**Comment by plokky** [comment]
sorry r9 i didnt see you wanted to do this but i pushed up the changes for this - everything needed is already there (no css needed), it's just putting through the right props + moving around onClicks so it works with closed role still.

**Comment by pikulet** [comment]
Fixed in #149
