### ISSUE TITLE
suggestion(core,major): remove "all" lobby

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#20]
by [drafterman](https://beyondmafia.com/community/forums/thread/IcXe6iehme?reply=qs3U26Iwm5)

Get rid of "all" lobby

by [Felix](https://beyondmafia.com/community/forums/thread/IcXe6iehme?reply=jOvDLlBgsgE)

i wanna stress how necessary this is cuz it would be a very easy mistake for new users or ppl just unaware to join a sandbox game first things first and end up upset over the lack of order. alternatively you can keep the all tab but Please. For the love of god. Not as the default.

**Comment by r3ndd** [comment]
It's only there temporarily to help the playerbase during launch.
