### ISSUE TITLE
bug: Witch control target vegging causes target to veg instead

### ISSUE THREAD

**Issue by ChaoticNeutralGnome** [r3ndd/BeyondMafia-Integration#232]
Witch control target vegging causes target to veg instead. The person who initially vegged is still alive, though cannot speak or perform actions, and won't veg any following day. 

![image](https://user-images.githubusercontent.com/38019116/216068028-785bd628-3d74-49b5-a514-f7f52e50b00b.png)
![image](https://user-images.githubusercontent.com/38019116/216068069-24019d4c-ed5a-4ac3-947d-28f5ab2d392e.png)
![image](https://user-images.githubusercontent.com/38019116/216068118-3d334249-5007-4ea1-830d-522709913894.png)
![image](https://user-images.githubusercontent.com/38019116/216068152-589d6e6f-327d-43f6-a99e-3fc7aa9ff73f.png)

**Comment by pikulet** [comment]
- tried making priority a level -999 action
- it vegges the correct target but the witch's target will "leave game"
- can we remove "leave game" from the veg logic anyway?

**Comment by ChaoticNeutralGnome** [comment]
This bug also affects driver/cyclist

**Comment by ChaoticNeutralGnome** [comment]
> * tried making vegging a priority -999 action
> * it vegges the correct target but the witch's target will "leave game"
> * can we remove "leave game" from the veg logic anyway?

I think we should do that. Is there a PR for your change?

**Comment by pikulet** [comment]
No I don't have a PR go ahead and make a fix @ChaoticNeutralGnome
