### ISSUE TITLE
bug(dreamer): can receive a dream while dead

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#296]
by [drafterman](https://beyondmafia.com/community/forums/thread/tbQ8YNKC2C?reply=vcsTmwPea)

[game link](https://beyondmafia.com/game/Pk-WERHn_)

---
need to decide if this is intended

**Comment by DrSharky** [comment]
> by [drafterman](https://beyondmafia.com/community/forums/thread/tbQ8YNKC2C?reply=vcsTmwPea)
> 
> [game link](https://beyondmafia.com/game/Pk-WERHn_)
> 
> need to decide if this is intended

I don't think this is intended. Even for graveyard roles, if you are dead as dreamer, the role should not act.
