### ISSUE TITLE
documentation: outdated readme

### ISSUE THREAD

**Issue by Kaltzisp** [r3ndd/BeyondMafia-Integration#32]
Readme could probably use an update to at the very least point to the docs pikulet has created - some of the other points could also possibly be brought up to date depending on what your plans are @r3ndd ? Partially raising this issue to get an idea of what you think, and partially so that we can set up a more unified set of instructions for would-be contributors like myself.

Not sure if you intend to re-add a dev branch for contributions or if you think it's not a priority atm since there aren't a massive number of contributors. Similarly, I'm not aware if https://test.beyondmafia.com/ is in the cards right now, perhaps you can advise?

**Comment by r3ndd** [comment]
Right now I don't think there's enough devs/testers for a dedicated test server to be useful, so it'd probably be best to update the README to just ask people to make pull requests on master.

@pikulet Feel free to add links to all of your documentation in the main readme!

**Comment by pikulet** [comment]
the readme is pretty decent now
