### ISSUE TITLE
feat(voting): add kicks mechanic

### ISSUE THREAD

**Issue by Fsalker** [r3ndd/BeyondMafia-Integration#330]
blocks #334 #335 

# (1) Kicks

**check "BeyondMafia Game Mechanics Change Suggestions" doc**

**Comment by pikulet** [comment]
#122 is a duplicate

**Comment by pikulet** [comment]
The formula for how many kicks are required to  is as follows: n/3 (always rounded UP), where n represents the number of living players in a game.

After all required kicks have been reached, a 15-second autokick timer will commence with an audible ping to warn users, at the end of which, the day phase will end, and all players who have not voted will turn into vegetables.

Kicks should not appear in the game voting log for living or dead players; however it is important for people reviewing the game to be able to view this information for moderation and/or learning purposes.

Kicks as a typing function (i.e. /kick) should be possible too, as well as simply clicking the kick. Obviously a user shouldn’t be able to kick twice in the same day or night phase by doing both.

**Comment by DrSharky** [comment]
Estimating around 5-7 work days, maybe more. The amount of work between the front end and back end, as well as the logic to insert this component into the game is complicated. Bugs will be formed, and we need to test and reduce them.
