### ISSUE TITLE
feat(ui): add role markers

### ISSUE THREAD

**Issue by Fsalker** [r3ndd/BeyondMafia-Integration#333]
# (6) Role Markers

![image](https://user-images.githubusercontent.com/16700631/221033095-6b73b313-94da-4d90-ab6f-fe0d86d4527b.png)

Clicking the `?` (**QUESTION MARK**) icon SHOULD ALLOW you to 'guess' the player's role.
- Clicking `?` reveals a dropdown containing ONLY roles included in the currently played setup
- BOTH alive & dead players can guess 
- the UI should indicate all roles you are currently guessing, in ANY REASONABLE way* _(it's up to you, we don't have a designer)_

*example:
![image](https://user-images.githubusercontent.com/16700631/221034198-3c2a5334-4a72-4225-8baf-4de3d9786ff0.png)

# EM Example

![image](https://user-images.githubusercontent.com/16700631/221360413-0ced2e5e-ec84-4b66-adfe-643a450e0738.png)
---
![image](https://user-images.githubusercontent.com/16700631/221360475-c7af1ec6-1132-4afd-8c96-0d5fb0646b5e.png)

https://www.youtube.com/watch?v=tbJe7giS7JY&t=513s

**Comment by DrSharky** [comment]
Estimating 5-7 work days. This is a new React element, most likely using Popover as a template. It seems like a more fleshed out feature to implement that may take a while.

**Comment by DrSharky** [comment]
Completed in #450
