### ISSUE TITLE
bug(dark mode): chat bubble not visible

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#400]
and can make it match the text colour

https://discord.com/channels/1047222060667125810/1079718540644462672

[reference](https://github.com/r3ndd/BeyondMafia-Integration/blob/master/react_main/src/pages/Game/Game.jsx#L1489)

![image](https://user-images.githubusercontent.com/24848927/222450579-c9c38185-683a-4c90-a74e-1db8ab863d8f.png)

**Comment by DrSharky** [comment]
Fixed in #426
