### ISSUE TITLE
Miscellaneous Resistance Bugs

### ISSUE THREAD

**Issue by starryburst** [r3ndd/BeyondMafia-Integration#455]
![Bug](https://cdn.discordapp.com/attachments/1064461269291241492/1082896480693669949/Screen_Shot_2023-03-07_at_9.23.55_PM.png)

![Bug2](https://media.discordapp.net/attachments/1064461269291241492/1082893645637758986/Screen_Shot_2023-03-07_at_9.12.39_PM.png?width=905&height=428)

- The "person" is leader and the team size messages appear multiple times (not sure exactly what triggers it)
- In post game meetings still happen and multiple "Group" chats were able to be created with actions which were still available in postgame

**Comment by pikulet** [comment]
unable to reproduce
