### ISSUE TITLE
bug(mastermind):  Mastermind role can be figured out by whispers and night meeting votes.

### ISSUE THREAD

**Issue by monkney** [r3ndd/BeyondMafia-Integration#488]
Mastermind  in an anonymous mafia meeting, mafia members can still whisper to all attendee's (this allows the mafia to determine who the mm is) meaning they can gang up and kill the MM in the night meeting straight away.

Also, in epicmafia all members of an anon mafia meeting could vote any player (mafia incl) for the kill meeting, thereby making it truly anonymous for both MM and mafia.

**Comment by pikulet** [comment]
1. (already works) mafia members cannot whisper anyone in the night meeting when mm is in game
2. (tofix) mafia kill currently excludes mafia members, should include them

**Comment by pikulet** [comment]
I think it happens when the person has a night action like hooker + MM can see whispers

**Comment by monkney** [comment]
Pretty sure this is already solved - will report back if that changes.
