### ISSUE TITLE
feat(forum,moderation): allow mods to edit posts by others

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#50]
by [DkKoba](https://beyondmafia.com/community/forums/thread/81ZRbzex0)

Ability for moderators to edit posts - primarily for official announcement posts, or when they wish to remove only a small rulebreaking part of a post and preserve the overall post, for instance, and down the line to enable this for forum mafia when things may need to be redacted

**Comment by pikulet** [comment]
https://github.com/r3ndd/BeyondMafia-Integration/issues/51 should also be able to edit thread titles

**Comment by Kaltzisp** [comment]
Implementation should ideally make it clear that the post has been edited by a Mod (e.g. “Edited by EvilAdmin123”



Another good idea from DkKobba was to colour any mod additions differently to show was text was added. A [redacted] label would also be great for deletions

**Comment by pikulet** [comment]
should hold off implementing this until we have a more solid idea of what to implement
