### ISSUE TITLE
bug(moderation): Censors don't turn on after being removed from mod group.

### ISSUE THREAD

**Issue by DrSharky** [r3ndd/BeyondMafia-Integration#511]
If you are added as a moderator/admin, and then you turn on the "disable all censors" option in the user settings, then remove the user from the moderator/admin group, the user can no longer access the option to turn off the disable all censors option, even if it is still on for them. The user can also no longer see the "Disable PG-13 censor" option.

The intended use case should be that if the user is removed from mod/admin group, the censor settings should reset. At least, the "disable all censors" one should.

**Comment by pikulet** [comment]
would restarting the server address this issue

**Comment by pikulet** [comment]
not needed due to new censor implementation
