### ISSUE TITLE
[totest] reviving guised person

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#561]
does it work, is it bugged?

**Comment by DrSharky** [comment]
Pretty sure it works. it swaps identities completely. I've tested it before, although there may be more extensive tests to be done.

**Comment by pikulet** [comment]
I posted this because some people have said that the **intended behaviour** when you are revived is to "unswap" the identity.

I'm fine with the current implementation, and I think doing "unswap" will be very complex with swap chains.
