### ISSUE TITLE
feat(pregame): let host have rainbow text

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#574]
There have been repeated suggestions to make the host of the game more obvious.

We can let the host have rainbow text in the pregame.

**Comment by KaIakaua** [comment]
Perpaps not a forced rainbow but a toggleable option in the in-game options section to switch between user normal colors and rainbow colors?

**Comment by pikulet** [comment]
im fine with other methods of host visibility outside of rainbows colours

**Comment by pikulet** [comment]
goals are not decided
