### ISSUE TITLE
bug: On the learn page the thief and courier roles are switched

### ISSUE THREAD

**Issue by monkney** [r3ndd/BeyondMafia-Integration#576]
![image](https://user-images.githubusercontent.com/127843894/228222475-47b0a0f5-804f-4da5-b070-94ea464853fe.png)

**Comment by pikulet** [comment]
@TheBeepich is aware of it, pinging in case

**Comment by TheBeepich** [comment]
yea i pr the fix but i must fix my fix

**Comment by starryburst** [comment]
Resolved in latest site update
