### ISSUE TITLE
bug(graveyard effects): dead people still have effects like insanity and blindness

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#58]
insanity - by [bri_](https://beyondmafia.com/community/forums/thread/jed4UrCsb)
blindness - by [drafterman](https://beyondmafia.com/community/forums/thread/tbQ8YNKC2C?reply=YN4biZob-G)

**Comment by pikulet** [comment]
We should also remove effects from everyone when the game ends, preventing issues like #57

**Comment by r3ndd** [comment]
Due to revival mechanics, I think dead players should keep effects and items.
