### ISSUE TITLE
bug(leave game): user does not leave game after logging out

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#61]
by [RickSanchez](https://beyondmafia.com/community/forums/thread/9_HpMN4cb)

I was switching from my MrNimbus alt to this account and I was waiting inside a pregame. I signed out but didn't leave the game and upon re-joining as rick my MrNimbus account was still in the game. What's good however is that I couldn't use the MrNimbus account to talk/see in anyway as when I refreshed it logged me into the correct account.

**Comment by r3ndd** [comment]
I mean this is basically just multiaccounting. Ranked will block multiple users from the same IP.
