### ISSUE TITLE
bug(voting): voting for dead player causes veg

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#62]
by [Imply](https://beyondmafia.com/community/forums/thread/0AuXMSWVZ)

Hello.

We can vote for dead people who were alive at the time of voting. I mean you vote someone, this person gets shot and your vote is still there. The problem comes when everybody votes as the day is hammered and everybody voting dead people vegs.

[Game](https://beyondmafia.com/game/ZOlMOFqEFh/review) - look day 2

To replicate the bug, do the following:
1. Vote for another player.
2. Get the player shot.
3. Have the remaining players vote.

---
in EM, the vote would switch to "a dead person" or something like that, and the timer would reset. (my guess) The timer does not reset when a vote is on a dead person (should count as an "unvote/ action" when they are shot, extending the timer)

**Comment by r3ndd** [comment]
I believe this is now fixed. Reopen if not.
