### ISSUE TITLE
bug(cop report): "the" appears twice

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#629]
![image](https://user-images.githubusercontent.com/24848927/230394051-9c0a877b-4303-4241-a787-b91b759ba5d7.png)

**Comment by raptor-07** [comment]
![image](https://user-images.githubusercontent.com/99596007/230558396-47358df8-4e17-4d54-93bf-ff2a4865161d.png)

alignment string has 'the' added twice. Changing this error in AlignmentLearner.js file and pulling req.

**Comment by starryburst** [comment]
Resolved in latest site update #633
