### ISSUE TITLE
bug(system message): second bread message has no icon

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#630]
![image](https://user-images.githubusercontent.com/24848927/230394422-4cfeddf8-c375-42c7-9073-35f3f20150e2.png)

**Comment by raptor-07** [comment]
Hey! Figured out this issue occurs because the string passed onto the alert is missing the ":sy2c:" word, which I am guessing is replaced dynamically. Please assign it to me. 
QUERY:  To which branch should I PR? The readme file mentions the "dev" branch which I am not able to find!
