### ISSUE TITLE
bug(poison, chemist): poison delay of 2 days instead of 1 day, reason unknown

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#67]
by [dooze](https://beyondmafia.com/community/forums/thread/IcXe6iehme?reply=IPbjn6xoDo)

https://beyondmafia.com/game/QwhBeNE8Ve

---
shayneismyname was poisoned on n0. --> d1 --> n1 --> d2.
they should have died on d2 since the poison effect has a delay of 1.
however, they died on d3 instead.

**Comment by r3ndd** [comment]
This is a very old game and was due to a now fixed Archer bug.
