### ISSUE TITLE
bug(daystart): mafia should not know partners on daystart

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#68]
by [hope](https://beyondmafia.com/community/forums/thread/IcXe6iehme?reply=-QAZU6Utc_)

---
lore wise, partners should only be revealed at night since that is when they "meet".

this mechanic changes how TSIB is played, since mafia has more cc power on the first day.

if this was intended, then make it configurable for mafia to know partners on daystart

**Comment by dkkoba** [comment]
It is not the intent to allow mafia to be uninformed at any point in the game.
