### ISSUE TITLE
feat(role markers): save state on refresh

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#722]

**Comment by pikulet** [comment]
@DrSharky is it a user expectation for state to persist on refresh? i want to avoid writing the state of the predictions to the backend

**Comment by DrSharky** [comment]
I really don't think so, to be honest. Would be nice, but I don't think it's expected. We can come back to this at a much later point and it wouldn't be a problem. So far I've only seen 1 person mention it, and they didn't expect it to persist on refresh.
