### ISSUE TITLE
bug(cyclist/ driver): they are visiting roles; wrong role description

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#723]

**Comment by Udassi-Pawan** [comment]
I would like to work on this issue, would you assign me?

**Comment by pikulet** [comment]
@Udassi-Pawan Alright assigned. Please change the last point of the description to only state that

- Redirection cannot be role blocked

We are removing the clause on visiting because the "visiting" behaviour is acknowledged as a default.
