### ISSUE TITLE
feat(profile): support more text customisation

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#75]
by [sofia](https://beyondmafia.com/community/forums/thread/IcXe6iehme?reply=rbjShG3sJJ)

more customization features for profiles would be nice, like being able to use commands such as center/ color/ size/ when typing out bios

**Comment by pikulet** [comment]
see #46 and react-markdown

**Comment by r3ndd** [comment]
50 token bounty for this and #46 combined.
