### ISSUE TITLE
feat(in-game,wills): add message when will is saved

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#76]
by [maxie](https://beyondmafia.com/community/forums/thread/IcXe6iehme?reply=MusP6bG0t)

silly but can we bring back the "your will has been updated" bit i like the reassurance that i didnt get cut off and my will is saved when i click off or the day changes

**Comment by r3ndd** [comment]
The will is saved on every keystroke. I don't think this is particularly necessary.
