### ISSUE TITLE
bug(dark mode settings): default is dark but shows light

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#768]
just a visual issue, the list should show auto as the first option

![image](https://user-images.githubusercontent.com/24848927/235172931-158372ba-c9b4-414a-a24c-5054e9d86f95.png)

**Comment by GFerreiroS** [comment]
Done! I have opened a pull for it [#782](https://github.com/r3ndd/BeyondMafia-Integration/pull/782)
