### ISSUE TITLE
feat(paid feature): pay to be a moderator

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#819]
by nyouhas, 100 000 tokens

i think this might be a joke idk, or some form of mega site sponsorship

**Comment by DrSharky** [comment]
???? Go ahead and close this probably

**Comment by monkney** [comment]
yeah this don't relaly make sense

**Comment by Thisinthat** [comment]
Yeah this was a joke.  Sorry if it confused you.  (I thought it was funny)
