### ISSUE TITLE
bug(forum): name colour is off

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#827]
![image](https://user-images.githubusercontent.com/24848927/236115716-f146a69a-0940-4e2a-a3be-24b53039aba7.png)

**Comment by DrSharky** [comment]
It's when you use the light theme, and it has to do with the contrast color fix I put in. I think some extra css label on the user names in the forums might fix it, so it doesn't affect these, but affects the usernames in game.

**Comment by pikulet** [comment]
Fixed by #fix(f
