### ISSUE TITLE
suggestion(role icon): mirror cultist and serial killer to face left

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#88]
by [LeEpicH](https://beyondmafia.com/community/forums/thread/IcXe6iehme?reply=i-pQzzi03)

mirror the role icons of cultist and serial killer so that they look the other direction. like in EM every role that doesnt let town win while its alive should look left

**Comment by pikulet** [comment]
@TheBeepich Could you handle this?

**Comment by TheBeepich** [comment]
I gotcha!
