### ISSUE TITLE
suggestion(janitor): default behaviour should not be one shot

### ISSUE THREAD

**Issue by pikulet** [r3ndd/BeyondMafia-Integration#91]
by [LeEpicH](https://beyondmafia.com/community/forums/thread/IcXe6iehme?reply=T08Yi1_sy)

janitor should be able to use their ability more than one per game by default

---
the "one shot" modifier can be used to make janitor one shot

**Comment by r3ndd** [comment]
To reduce confusion I'm going to leave it like it was on EM for now.
