### ISSUE TITLE
bug(frontend): Clicking on game name at the top of the page doesn't open BM in new tab.

### ISSUE THREAD

**Issue by DrSharky** [r3ndd/BeyondMafia-Integration#95]
Since the code was changed to this: 
```
function onLogoClick() {
		window.open(process.env.BASE_URL, "_blank");
	}
```
This feature no longer works.
It did work when the beyondmafia address was specified in the call to the open function.

**Comment by plokky** [comment]
sorry i broke it but i fixed it
