### ISSUE TITLE
bug(executioner): If Executioner wins during an anon day, the anon chat persists to postgame

### ISSUE THREAD

**Issue by DrSharky** [r3ndd/BeyondMafia-Integration#97]
Bug description: Winning as executioner during an anonymous day will result in the postgame chat remaining anonymous.

Steps to replicate: Start a game with witch & executioner. Kill the witch. Kill the executioner's target. Note that the postgame chat is anonymous.
Review the game for reference:
https://beyondmafia.com/game/VUMU3QDdr

**Comment by pikulet** [comment]
#57 same report

**Comment by pikulet** [comment]
bug(effects): players retain effects like blindness and insanity in the postgame
